# Generated by Django 5.1 on 2024-08-08 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('documento_identidad', models.CharField(max_length=50, unique=True)),
                ('tipo_asistente', models.CharField(choices=[('empleado', 'Empleado'), ('proveedor', 'Proveedor'), ('invitado', 'Invitado')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_empleado', models.CharField(choices=[('sistemas', 'Sistemas'), ('mercadeo', 'Mercadeo'), ('produccion', 'Producción'), ('gestion humana', 'Gestión Humana')], max_length=20)),
                ('asistente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asistencia.asistente')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_ingreso', models.DateTimeField()),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('motivo_antes_16', models.TextField(blank=True, null=True)),
                ('asistente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.asistente')),
            ],
        ),
    ]
