# Generated by Django 5.1 on 2024-08-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistente',
            name='documento_identidad',
            field=models.CharField(max_length=50),
        ),
    ]
