# Generated by Django 5.1 on 2024-08-08 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_alter_empleado_tipo_empleado'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registroasistencia',
            table='asistencia_registroasistencia',
        ),
    ]
